# -*- coding: utf-8 -*-
"""slr.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbT_O53yjkiVqSEEuJUIrQTUoJwkLTaC
"""

import numpy as np # linear algebra
import pandas as pd

# from subprocess import check_output # This line commonly causes errors in Colab as the '../input' directory doesn't exist.
# print(check_output(["ls", "../input"]).decode("utf8"))

# Any results you write to the current directory are saved as output.

#Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# np.set_printoptions(threshold=np.nan) # This line caused a ValueError. 'threshold' must be an integer, not np.nan. You can remove it or use a large integer like `sys.maxsize` if you want to prevent truncation.


#Importing DataSet
# dataset = pd.read_csv(r'C:\Users\HP\Downloads\house_data.csv') # This is a local file path and will not work in Colab. You need to upload your data or provide a Colab-compatible path.
# Placeholder for dataset loading. Replace with your actual data loading method for Colab.
dataset = pd.DataFrame({'sqft_living': np.random.rand(100)*1000 + 1000, 'price': np.random.rand(100)*500000 + 100000})

space=dataset['sqft_living']
price=dataset['price']

x = np.array(space).reshape(-1, 1)
y = np.array(price)

#Splitting the data into Train and Test
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=1/3, random_state=0)


#Fitting simple linear regression to the Training Set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(xtrain, ytrain)

#Predicting the prices
pred = regressor.predict(xtest)

#Visualizing the training Test Results
plt.scatter(xtrain, ytrain, color= 'red')
plt.plot(xtrain, regressor.predict(xtrain), color = 'blue')
plt.title ("Visuals for Training Dataset")
plt.xlabel("Space")
plt.ylabel("Price")
plt.show()

#Visualizing the Test Results
plt.scatter(xtest, ytest, color= 'red')
plt.plot(xtrain, regressor.predict(xtrain), color = 'blue')
plt.title("Visuals for Test DataSet")
plt.xlabel("Space")
plt.ylabel("Price")
plt.show()